// Package router assembles the HTTP handler chain. It is the only
// place that knows about concrete URL paths, so renaming or
// versioning the API is a one-file change.
package router

import (
	"log/slog"
	"net/http"

	httpSwagger "github.com/swaggo/http-swagger"
	_ "github.com/Camilo404/go-api-template/docs" // generated by `make swag`; registers the OpenAPI spec.

	"github.com/Camilo404/go-api-template/internal/config"
	"github.com/Camilo404/go-api-template/internal/handlers"
	"github.com/Camilo404/go-api-template/internal/middleware"
	"github.com/Camilo404/go-api-template/internal/service"
)

// Deps groups the dependencies the router needs. Adding a new
// dependency (e.g. another service) means adding a field here and
// plumbing it through main.
type Deps struct {
	Config *config.Config
	Logger *slog.Logger
	// Service is the example business service. Add your own below.
	Tasks *service.TaskService
}

// New builds the top-level http.Handler. Middleware order, from
// outermost to innermost:
//
//  1. RequestID  - propagates X-Request-ID for log correlation
//  2. Recovery   - catches panics anywhere downstream
//  3. Logging    - emits one structured log line per request
//  4. CORS       - sets headers and answers preflight requests
func New(d Deps) http.Handler {
	mux := http.NewServeMux()

	// Liveness/readiness - unauthenticated, never versioned.
	mux.Handle("/health", handlers.NewHealthHandler())

	// OpenAPI / Swagger UI. Only mounted when explicitly enabled so
	// production deployments are not forced to expose the schema.
	if d.Config.EnableSwagger {
		mux.Handle("/swagger/", httpSwagger.Handler(httpSwagger.URL("doc.json")))
	}

	// Versioned API surface. /api/v1/... is stripped before being
	// dispatched to the version-local mux so handlers can register
	// paths relative to /tasks.
	v1 := http.NewServeMux()
	tasks := handlers.NewTaskHandler(d.Tasks, d.Config.MaxBodyBytes)
	v1.Handle("/tasks", tasks)
	v1.Handle("/tasks/", tasks)
	mux.Handle("/api/v1/", http.StripPrefix("/api/v1", v1))

	return middleware.Chain(mux,
		middleware.RequestID,
		RecoveryOrNil(d.Logger),
		middleware.Logging(d.Logger),
		middleware.CORS(d.Config.CORSOrigins),
	)
}

// RecoveryOrNil returns Recovery if a logger is configured, otherwise
// a passthrough. It keeps the router testable without a logger.
func RecoveryOrNil(logger *slog.Logger) middleware.Middleware {
	if logger == nil {
		return func(next http.Handler) http.Handler { return next }
	}
	return middleware.Recovery(logger)
}
